apiVersion: v1
appVersion: "1.0"
description: PyTorch是一款使用GPU和CPU优化的开源深度学习平台,提供从研究原型到生产部署的无缝路径。它通过混合前端、分布式培训和工具和库生态系统实现快速、灵活的实验和高效生产。
name: pytorch
icon: https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png
version: 0.3.2
